services:
  generator:
    image: alpine:3.18
    volumes:
      - ./:/workdir
    working_dir: /workdir
    # Install openssl and node tools so deploy_fixed.sh can generate a package-lock and certs
    command: /bin/sh -c "apk add --no-cache openssl nodejs npm && chmod +x ./deploy_fixed.sh ./deploy/nginx/generate-selfsigned.sh && ./deploy_fixed.sh && ./deploy/nginx/generate-selfsigned.sh"
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  solana-test-validator:
    image: solanalabs/solana:v1.14.17
    ports:
      - "8899:8899"
    command: solana-test-validator --reset
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  oracle-ai:
    build: ./services/oracle-ai
    ports:
      - "5001:5001"
    depends_on:
      - generator
      - solana-test-validator
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD-SHELL","curl -f http://localhost:5001/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  portal-webapp:
    build: ./client/vaos-portal
    ports:
      - "3000:3000"
    depends_on:
      - generator
      - oracle-ai
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD-SHELL","curl -f http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  reverse-proxy:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./deploy/nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - generator
      - portal-webapp
      - oracle-ai
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
